name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build check
      - name: Upload To Pgyer
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://www.pgyer.com/apiv2/app/upload
          method: POST
          forms: '{"_api_key":"${{ secrets.PGYERTOKEN }}","buildInstallType":3}'
          fileForms: '{"file":"app/build/outputs/apk/debug/xw-debug.apk"}'
#      - uses: actions/cache@preview
#        id: cache
#        with:
#          path: ~/local/rubies
#          key: ruby-2.6.5
#      - uses: clupprich/ruby-build-action@master
#        id: ruby
#        with:
#          ruby-version: 2.6.5
#          cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
#      - name: install fir.im
#        run: gem install fir-cli
#      - name: Upload to Fir.im
#        run: fir login ${{ secrets.FIRTOKEN }}
#      - run: fir publish app/build/outputs/apk/release/app-release.apk